include_guard(GLOBAL)
message(STATUS "${CMAKE_CURRENT_LIST_FILE} component is included.")

if (NOT DEFINED ENV{ARMGCC_DIR})
	MESSAGE(FATAL_ERROR "$ENV{ARMGCC_DIR} have to be defined!")
endif()
if (NOT DEFINED ENV{LIBRARY_TYPE})
	SET(LIBRARY_TYPE REDLIB)
endif()
if (NOT DEFINED ENV{LANGUAGE})
	SET(LANGUAGE C)
endif()
if (NOT DEFINED ENV{DEBUG_CONSOLE})
	SET(DEBUG_CONSOLE UART)
endif()




