/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_B0_12 (coord K14), UART1_TXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                       TX   /*!< Signal name */

/* GPIO_AD_B0_13 (coord L14), UART1_RXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                       RX   /*!< Signal name */

/* GPIO_SD_B1_03 (coord M4), LED1 */
/* Routed pin properties */
#define BOARD_INITPINS_ALIVE_LED_PERIPHERAL                                GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_ALIVE_LED_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ALIVE_LED_CHANNEL                                      3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ALIVE_LED_GPIO                                      GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ALIVE_LED_GPIO_PIN                                     3U   /*!< GPIO pin number */
#define BOARD_INITPINS_ALIVE_LED_GPIO_PIN_MASK                        (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ALIVE_LED_PORT                                      GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ALIVE_LED_PIN                                          3U   /*!< PORT pin number */
#define BOARD_INITPINS_ALIVE_LED_PIN_MASK                             (1U << 3U)   /*!< PORT pin mask */

/* GPIO_SD_B1_04 (coord P2), LED2 */
/* Routed pin properties */
#define BOARD_INITPINS_PROCESS_LED_PERIPHERAL                              GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_PROCESS_LED_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_PROCESS_LED_CHANNEL                                    4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PROCESS_LED_GPIO                                    GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_PROCESS_LED_GPIO_PIN                                   4U   /*!< GPIO pin number */
#define BOARD_INITPINS_PROCESS_LED_GPIO_PIN_MASK                      (1U << 4U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_PROCESS_LED_PORT                                    GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_PROCESS_LED_PIN                                        4U   /*!< PORT pin number */
#define BOARD_INITPINS_PROCESS_LED_PIN_MASK                           (1U << 4U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
